university_locations = {
    "VA": ["College of William Mary", "University of Virginia", "Virginia Tech"],
    "NY": [
        "University of Rochester",
        "Cornell University",
        "New York University",
        "Lehigh University",
        "Columbia University",
        "Fordham University",
        "University at Buffalo--SUNY",
        "Stony Brook University--SUNY",
        "Syracuse University",
        "Rensselaer Polytechnic Institute",
    ],
    "GA": ["Emory University", "Georgia Institute of Technology"],
    "CA": [
        "University of California--Berkeley",
        "University of California--Los Angeles",
        "University of California--San Diego",
        "University of California--Irvine",
        "University of Southern California",
        "Stanford University",
        "California Institute of Technology",
        "University of California--Santa Barbara",
        "University of California--Davis",
        "University of California--Santa Cruz",
        "Pepperdine University",
        "University of San Diego",
        "Santa Clara University",
        "University of California--Merced",
        "University of California--Riverside",
    ],
    "PA": [
        "Carnegie Mellon University",
        "University of Pennsylvania",
        "Lehigh University",
        "University of Pittsburgh--Pittsburgh Campus",
    ],
    "MA": [
        "Harvard University",
        "Boston University",
        "Tufts University",
        "Northeastern University",
        "Massachusetts Institute of Technology",
        "Brandeis University",
        "Boston College",
        "Worcester Polytechnic Institute",
    ],
    "IL": [
        "Northwestern University",
        "University of Illinois at Urbana-Champaign",
        "University of Chicago",
    ],
    "OH": ["Case Western Reserve University"],
    "CT": ["Yale University"],
    "MD": ["Johns Hopkins University", "University of Maryland--College Park"],
    "NC": [
        "Wake Forest University",
        "Duke University",
        "University of North Carolina at Chapel Hill",
        "Elon University",
        "North Carolina State University",
    ],
    "IN": [
        "University of Notre Dame",
        "Purdue University--West Lafayette",
        "Indiana University--Bloomington",
    ],
    "FL": ["University of Florida", "Florida State University", "University of Miami"],
    "DC": [
        "Georgetown University",
        "Howard University",
        "American University",
        "George Washington University",
    ],
    "TN": ["Vanderbilt University"],
    "TX": [
        "University of Texas at Austin",
        "Rice University",
        "Texas A&M University",
        "Southern Methodist University",
        "Baylor University",
    ],
    "LA": ["Tulane University"],
    "MO": ["Washington University in St Louis"],
    "MI": ["University of Michigan", "Michigan State University"],
    "RI": ["Brown University"],
    "NJ": [
        "Princeton University",
        "Rutgers University--New Brunswick",
        "Stevens Institute of Technology",
    ],
    "NH": ["Dartmouth College"],
    "AL": ["Auburn University"],
    "UT": ["Brigham Young University--Provo"],
    "SC": ["Clemson University"],
    "CO": ["University of Denver", "Colorado School of Mines"],
    "WI": ["University of Wisconsin--Madison", "Marquette University"],
    "WA": ["University of Washington", "Gonzaga University"],
    "AZ": ["University of Arizona"],
    "MA": ["Worcester Polytechnic Institute"],
    "MN": ["University of Minnesota--Twin Cities"],
    "PA": ["Pennsylvania State University--University Park"],
    "NJ": ["Stevens Institute of Technology"],
    "NJ": ["Rutgers University--New Brunswick"],
    "NJ": ["Yeshiva University"],
}
